<?php

require_once drupal_get_path('module', 'data_exchange') .'/includes/data_exchange.alter-form.inc';
require_once drupal_get_path('module', 'data_exchange') .'/includes/data_exchange.cron.inc';

if(is_null(\Drupal::state()->get('dataX'))) {
  \Drupal::state()->set('dataX', ['import' => [],'export' => []]);
}

/**
 *  Get all fields in specific content type
 */
function get_fields_in($content_type){
  $node_fields  =\Drupal::entityManager()->getFieldDefinitions('node',$content_type);
  $fields = [];
  foreach ($node_fields as $field_id => $info) {
    if(is_object($info) && $field_id != 'comment'){
      if(is_a($info, 'Drupal\field\Entity\FieldConfig') && (strpos($info->getType(), 'image') === false)){
        $fields[]= [
          'name' => $field_id,
          'label' => $info->label(),
          'type' => $info->getType(),
          'status' => 1,
          'key' => count($fields),
        ];
      }
    }
  }
  return $fields;
}