<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements of hook_init()
 */
function data_exchange_init(){
  if(is_null(\Drupal::config('data_exchange.settings')->get('dataX'))){
    \Drupal::config('data_exchange.settings')
        ->set('dataX', ['importable' => [],'exportable' => []])
        ->save();
  }
}

/**
 * Implements of hook_form_FORM_ID_alter()
 */
function data_exchange_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  $form['data_exchange'] = array(
    '#type' => 'details',
    '#title' => t('Data exchange settings'),
    '#open' => TRUE,
    '#weight' => 10,
    '#group' => 'additional_settings',
  );
  $isImportableNode = !empty($form['type']['#default_value'])?\Drupal::config('data_exchange.settings')->get($form['type']['#default_value'].'_importable'):0;
  $form['data_exchange']['importable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow to import data'),
    '#default_value' => $isImportableNode
  );
  $isExportableNode = !empty($form['type']['#default_value'])?\Drupal::config('data_exchange.settings')->get($form['type']['#default_value'].'_exportable'):0;
  $form['data_exchange']['exportable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow to export data'),
    '#default_value' => $isExportableNode
  );
  $form['actions']['submit']['#submit'][] = 'data_exchange_node_type_submit';
}

/**
 * {@inheritdoc}
 * Settings content type :: data_exchange submission part
 */
function data_exchange_node_type_submit($form, FormStateInterface $form_state){
  // $dataX = \Drupal::config('data_exchange.settings')->get('dataX');
  // /*$content_type = $form_state->getValue('type');
  // $node_fields = get_fields_in($content_type);
  // // Importability
  // $isImportable = $form_state->getValue('importable');
  // // \Drupal::config('data_exchange.settings')
  // //       ->set('dataX', $isImportable)
  // //       ->save();
  // if($isImportable && !isset($dataX['importable'][$content_type])){
  //   //$dataX['importable'][$content_type]=$node_fields;
  // }else{
  //   //unset($dataX['importable'][$content_type]);
  // }
  // // Exportability
  // $isExportable = $form_state->getValue('exportable');
  // // \Drupal::config('data_exchange.settings')
  // //       ->set('dataX', $isExportable)
  // //       ->save();
  // if($isExportable && !isset($dataX['exportable'][$content_type])){
  //   //$dataX['exportable'][$content_type]=$node_fields;
  // }else{
  //   //unset($dataX['exportable'][$content_type]);
  // }*/
  // dpm($dataX);
}

/**
 *  Get all fields in specific content type
 */
function get_fields_in($content_type){
  $node_fields  =\Drupal::entityManager()->getFieldDefinitions('node',$content_type);
  $fields = [];
  foreach ($node_fields as $field_id => $info) {
    if(is_object($info) && $field_id != 'comment'){
      if(is_a($info, 'Drupal\field\Entity\FieldConfig')){
        $fields[] = $field_id;
      }
    }
  }
  return $fields;
}